[tool.poetry]
name = "mlenv"
version = "0.1.0"
description = ""
authors = ["José M. Sánchez <tulkas72@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
